### ISSUE TITLE
Sphinx Build Error

### ISSUE THREAD

**Issue by Rickodesea** [mgeier/insipid-sphinx-theme#52]
Get this error when try to build with theme on Sphinx on Ubuntu 20.04:
``Exception occurred:
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 163, in __init__
    self.searchpath = list(searchpath)
TypeError: 'PosixPath' object is not iterable
``

### Traceback log:
```
# Sphinx version: 1.8.5
# Python version: 3.8.10 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.10.1
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/cmd/build.py", line 300, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 263, in __init__
    self._init_builder()
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 324, in _init_builder
    self.builder.init()
  File "/usr/lib/python3/dist-packages/sphinx/builders/html.py", line 329, in init
    self.init_templates()
  File "/usr/lib/python3/dist-packages/sphinx/builders/html.py", line 378, in init_templates
    self.templates.init(self, self.theme)
  File "/usr/lib/python3/dist-packages/sphinx/jinja2glue.py", line 190, in init
    self.loaders = [SphinxFileSystemLoader(x) for x in loaderchain]
  File "/usr/lib/python3/dist-packages/sphinx/jinja2glue.py", line 190, in <listcomp>
    self.loaders = [SphinxFileSystemLoader(x) for x in loaderchain]
  File "/usr/lib/python3/dist-packages/jinja2/loaders.py", line 163, in __init__
    self.searchpath = list(searchpath)
TypeError: 'PosixPath' object is not iterable
```

**Comment by Rickodesea** [comment]
The issue is resolved by upgrading python to Python3.9

**Comment by mgeier** [comment]
It should also work with Python 3.8 (and even lower), I think you might inadvertently have upgraded your Jinja2 version, which has to be at least version 2.11:

https://github.com/mgeier/insipid-sphinx-theme/blob/5391b5c2fb12e90fd931bd6b9c239886ce09ddef/setup.py#L27

See also #13.
